### PR TITLE
Download PDB using PInvoke

### LINKED ISSUE #10: Wrong URL for pdb install?
This mod is failing to download UnityPlayer pdb.

It seems that the mod is trying to download UnityPlayer_Win64_player_mono_x64.pd_ instead of UnityPlayer_Win64_player_mono_x64.pd**b**?
```
[Message:FixPluginTypesSerialization] Not using the config cache
[Info   :FixPluginTypesSerialization] Downloading : http://symbolserver.unity3d.com/UnityPlayer_Win64_player_mono_x64.pdb\A61EBFBE39CD4C79B464F38853DB30B51\UnityPlayer_Win64_player_mono_x64.pd_
This pdb file is needed for the plugin to work properly. This may take a while, relax, modding is coming.
[Error  :FixPluginTypesSerialization] Failed to initialize plugin types serialization fix: (System.Net.Http.HttpRequestException) An error occurred while sending the request. Some plugins may not work properly.
[Error  :FixPluginTypesSerialization] System.Net.Http.HttpRequestException: An error occurred while sending the request ---> System.Net.WebException: Invalid status code: 308 ---> System.Net.ProtocolViolationException: Invalid status code: 308
  at System.Net.HttpWebRequest.Redirect (System.Net.HttpStatusCode code, System.Net.WebResponse response) [0x000e2] in <6db90f4241f34718aade286911577a8a>:0 
  at System.Net.HttpWebRequest.CheckFinalStatus (System.Net.HttpWebResponse response) [0x0016f] in <6db90f4241f34718aade286911577a8a>:0 
  at System.Net.HttpWebRequest.GetResponseFromData (System.Net.WebResponseStream stream, System.Threading.CancellationToken cancellationToken) [0x0006f] in <6db90f4241f34718aade286911577a8a>:0 
  at System.Net.HttpWebRequest.MyGetResponseAsync (System.Threading.CancellationToken cancellationToken) [0x00307] in <6db90f4241f34718aade286911577a8a>:0 
   --- End of inner exception stack trace ---
  at System.Net.HttpWebRequest.RunWithTimeoutWorker[T] (System.Threading.Tasks.Task`1[TResult] workerTask, System.Int32 timeout, System.Action abort, System.Func`1[TResult] aborted, System.Threading.CancellationTokenSource cts) [0x000f8] in <6db90f4241f34718aade286911577a8a>:0 
  at System.Net.HttpWebRequest.EndGetResponse (System.IAsyncResult asyncResult) [0x00020] in <6db90f4241f34718aade286911577a8a>:0 
  at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <1071a2cb0cb3433aae80a793c277a048>:0 
--- End of stack trace from previous location where exception was thrown ---

  at System.Net.Http.MonoWebRequestHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x004ae] in <81a53b27557545fe94d71df32265c99f>:0 
   --- End of inner exception stack trace ---
  at System.Net.Http.MonoWebRequestHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x00509] in <81a53b27557545fe94d71df32265c99f>:0 
  at System.Net.Http.HttpClient.SendAsyncWorker (System.Net.Http.HttpRequestMessage request, System.Net.Http.HttpCompletionOption completionOption, System.Threading.CancellationToken cancellationToken) [0x000e8] in <81a53b27557545fe94d71df32265c99f>:0 
  at FixPluginTypesSerialization.Util.MiniPdbReader.DownloadFromWeb (System.String url) [0x00026] in <7e35fed9c5b3448891388d58e908306c>:0 
  at FixPluginTypesSerialization.Util.MiniPdbReader.DownloadUnityPdb (FixPluginTypesSerialization.Util.PeReader peReader) [0x0002f] in <7e35fed9c5b3448891388d58e908306c>:0 
  at FixPluginTypesSerialization.Util.MiniPdbReader..ctor (System.String targetFilePath) [0x00075] in <7e35fed9c5b3448891388d58e908306c>:0 
  at FixPluginTypesSerialization.FixPluginTypesSerializationPatcher.DetourUnityPlayer () [0x0001e] in <7e35fed9c5b3448891388d58e908306c>:0 
  at FixPluginTypesSerialization.FixPluginTypesSerializationPatcher.InitializeInternal () [0x00000] in <7e35fed9c5b3448891388d58e908306c>:0 
  at FixPluginTypesSerialization.FixPluginTypesSerializationPatcher.Initialize () [0x00005] in <7e35fed9c5b3448891388d58e908306c>:0 
```

### LINKED ISSUE #12: IsFileCreated crash on Unity 2022.3.62
With all the panic around the [recent Unity vulnerability](https://flatt.tech/research/posts/arbitrary-code-execution-in-unity-runtime/) a lot of games are updating their Unity version, with a common version being 2022.3.62f2 (since it's LTS, and safe from the vulnerability).

This new version has changed the internal structure that is passed to `IsFileCreated`, and even with the correct offsets, the current version of FPTS will crash the game as it's trying to read invalid memory.

I've done a bit of digging around, and found that this new structure is most likely a 24-bye structure which looks like this in memory:

Image

and the structure *may* look something like this:

```c
struct PARAM {
    char* data; // ANSI string
    unsigned long long size; // Uncertain of size, may be 64-bit, could be 32-bit, but I'm leaning towards 64-bit
    unsigned long long flags; // Just a guess
}
```

This structure is not compatible with any of the `IAbsolutePathString` implementations found in FPTS so far.

Here's what I assembled pretty quick which made FPTS work again:

```cs
        private struct Idk
        {
            public nint data;
            public ulong length;
        }

        private static unsafe bool OnIsFileCreated(IntPtr str)
        {
            Idk* ptr = (Idk*)str;

            var actualString = Marshal.PtrToStringAnsi(ptr->data, (int)ptr->length);

            Log.Debug($"IsFileCreated(0x{str.ToInt64():X2})");
            Log.Debug($"{actualString}");

            if (actualString is not null && FixPluginTypesSerializationPatcher.PluginNames.Any(actualString.EndsWith))
            {
                return true;
            }

            return original(str);
        }
```

I am however fairly certain that the parameter passed is not even an AbsolutePathString, as in the decompiled `IsFileCreated` function, a call to `FileSystem::ToAbsolute` is made, taking the first (and only) parameter as input. This combined with the fact that I have seen relative paths in this structure makes me believe that they're passing an entirely different struct into the `IsFileCreated` method.

So while my quick and dirty code works, it would obviously break on other Unity versions that do still use an AbsolutePathString.

@xiaoxiao921 what do you think is the best approach here? Just add a dirty `if` statement at the top checking the engine version? Making a separate patch for this Unity version? I'm not too familiar with this codebase so I don't know what the best course of action is here.

### PR DESCRIPTION
**Pull request by DaXcess**
For a while Unity has been enforcing HTTPS on their symbol servers, which is a problem because during the patcher phase in BepInEx, HTTPS is not yet supported.

This was initially fixed by shipping an external executable which would download the PDB file. This is however an undesirable solution for a couple of reasons:

- Having to ship an extra *executable* increases complexity
- Thunderstore's automated filters don't really like `Process.Start` and `ProcessStartInfo`
- ~~This technique only supports Windows (and *probably* Wine/Proton, but not Linux or MacOS native games)~~

A more elegant solution is to use PInvoke to use native system libraries to perform the download for us.

**Windows**

On Windows, we can leverage the `winhttp.dll` library to download the PDB files. `winhttp.dll` is used by BepInEx as the chainloader proxy anyways, so it's basically guaranteed to exist.

This project only seems to support Windows anyways, so Linux/MacOS support can be ignored

**Testing**

- [x] Windows
- [x] Linux (Wine/Proton)

### CODE REVIEW

**Comment by DaXcess** [comment]
image

PInvoke download works on Windows (had to replace `wininet` with `winhttp` because wininet was throwing PROC_NOT_FOUND errors). Since `winhttp` also is included with Wine/Proton this means that this also works in those contexts.

**Comment by xiaoxiao921** [comment]
Sorry for not backing to you before but i didn't merge and ignored this pr because to my mind there was just no specific reasons to merge as it was just a refactor of effectively an already working solution with no pros as i don't think the extra exe in a zip that is installed automatically by mod managers would change anything and that the TS filter was gonna trigger regardless due to the amount of native stuff this project is interacting with + your solution is using pinvokes which also trigger the filter anyway.

But i'm fine with moving ahead with this solution since you also support pd_ and pdb files. I'm also fine if you wanna solve #12 on this pr too i'll be happy to merge it

**Comment by DaXcess** [comment]
Okay, for #12 merged my `2022.3.62` branch into this PR.

The best thing I could come up with was adding a new property to `UseRightStructs` called `IsFileCreatedRelative`, which is currently only set whenever the Unity version is 2022.3.62 or higher, but flipped back to false if it's 2023+.

Then in the `IsFileCreated` hook I check if it's relative, and if so use `RelativePathString` instead of `AbsolutePathString` to read the path (which uses the already existing `GetStruct<T>` that already supports abstraction). Let me know if you think there's better ways to achieve this, otherwise I think this should be good.

File: src/FixPluginTypesSerialization/Patchers/IsFileCreated.cs [hunk 1]
```diff
@@ -46,8 +46,18 @@ internal static void Dispose()
 
         private static unsafe bool OnIsFileCreated(IntPtr str)
         {
-            var assemblyString = UseRightStructs.GetStruct<IAbsolutePathString>(str);
-            var actualString = assemblyString.ToStringAnsi();
+            string actualString;
+
+            if (UseRightStructs.IsFileCreatedRelative)
```
Comment (xiaoxiao921) [inline src/FixPluginTypesSerialization/Patchers/IsFileCreated.cs]: I don't get that if else statement, unless i'm missing something it's why we made the UseRightStructs abstraction in the first place, which pick the right struct to use while still using the same method calls through dynamic dispatch

Comment (DaXcess) [reply src/FixPluginTypesSerialization/Patchers/IsFileCreated.cs]: The parameter passed to `IsFileCreated` in this Unity version does not seem to be anything related to AbsolutePathString, so because I had to introduce a new struct, there needs to be something that can tell IsFileCreated to choose between the AbsolutePathString or the other struct. I did not want to create a new AbsolutePathString as I believe that struct itself might not have changed.

Comment (DaXcess) [reply src/FixPluginTypesSerialization/Patchers/IsFileCreated.cs]: The `ConvertSeparatorsToPlatform` still requires the use of the "current" AbsolutePathString (from v2021.v1), so that means if I added a new AbsolutePathString for v2022.v3.v62 to work with `IsFileCreated`, it would break the implementation for `ConvertSeparatorsToPlatform`.

Comment (DaXcess) [reply src/FixPluginTypesSerialization/Patchers/IsFileCreated.cs]: Basically what I'm saying is, the hook for `IsFileCreated` was built with the expectation that the parameter passed to it is always a pointer to *StringStorageDefault, however in this specific Unity version an entirely different struct is passed (whilst the AbsolutePathString itself is still the same as before), so the hook somehow needs to know which struct to use.

Comment (DaXcess) [reply src/FixPluginTypesSerialization/Patchers/IsFileCreated.cs]: Only other thing I can think of is adding something like an `IIsFileCreatedParam` abstraction, that'd at least get rid of the if shenanigans

Comment (xiaoxiao921) [reply src/FixPluginTypesSerialization/Patchers/IsFileCreated.cs]: Looks good to me, thanks!

File: src/FixPluginTypesSerialization/UnityPlayer/Structs/v5/v0/IsFileCreatedParam.cs [hunk 2]
```diff
@@ -0,0 +1,25 @@
+﻿using System;
+using FixPluginTypesSerialization.UnityPlayer.Structs.Default;
+
+namespace FixPluginTypesSerialization.UnityPlayer.Structs.v5.v0
+{
+    public class IsFileCreatedParam : IIsFileCreatedParam
```
Comment (KingEnderBrine) [inline src/FixPluginTypesSerialization/UnityPlayer/Structs/v5/v0/IsFileCreatedParam.cs:6]: You don't have an `ApplicableToUnityVersionsSince` so any version below 2022.3.62 will fail, you also don't have another `IsFileCreatedParam` for versions startig from 2023 so those also will fail. Only 2022.3.62 will work correctly.

**Comment by DaXcess** [comment]
This one got merged a 'lil too quickly, I was proposing the `IIsFileCreated` abstraction, but not fully implemented it yet. Should've probably converted it back into a draft.

Will scramble together another PR (draft this time) that fixes some of the missing implementations in this one.
